# Generated by Django 5.2 on 2025-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
