# Generated by Django 5.2 on 2025-05-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
