# Generated by Django 5.2 on 2025-05-04 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_scheduledclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledclass',
            name='class_link',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='title',
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
