# Generated by Django 5.2 on 2025-05-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_semester_courseschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_name',
        ),
    ]
