# Generated by Django 5.2 on 2025-05-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_teacher_course_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creator',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assigned_teacher',
        ),
    ]
